In [ ]:
print('hello world')

hello world


In [ ]:
def to_celcius(x):
    return (x-32) * 5/9
to_celcius(75)


23.88888888888889

In [ ]:
number = -4

if number > 0:
    print('number is positive')
elif number == 0:
    print('number is zero')
else:
    print('number is negative')


number is negative


In [ ]:
age_list = [1,2,3,4,5]

In [ ]:
max_age = max(age_list)
max_age

5

In [ ]:
max_age =str(max_age)
max_age

'5'

In [ ]:
type('A')

str

In [ ]:
print('2 + 2 = '+ str(2 + 2))

2 + 2 = 4


In [ ]:
def greeting (name):
    print('welcome, brou '+ name +'!!!')
    print('you have made it into google !')
greeting('Bryan')

welcome, brou Bryan!!!
you have made it into google !


In [ ]:
def area_triangle(base,height):
    return base *height/2
area_X = area_triangle(5,4)
area_Y = area_triangle(7,3)

total_area = area_X + area_Y

total_area

20.5

In [ ]:
def get_seconds(hours, minutes, seconds):
    total_seconds = 3600*hours + 60*minutes + seconds
    return total_seconds
get_seconds(16, 43, 50)

60230

In [ ]:
def lucky_number (name):
    number = len(name)*9
    print('hello '+ name + ', your lucky number is '+str(number))
lucky_number ('Bryan')
lucky_number ('Edbert')

hello Bryan, your lucky number is 45
hello Edbert, your lucky number is 54


In [1]:
def seed_calculator(fountain_side, grass_width):
    fountain_area = fountain_side**2
    total_area = (fountain_side +2 * grass_width) **2
    grass_area = total_area - fountain_area
    seed = grass_area *35
    seed = seed/1000
    return seed
seed_calculator (12,2)





3.92

In [3]:
print (1==2)

False


In [4]:
print('yellow'> 'cyan' and 'brown' >'magenta')

False


In [6]:
print (not 42 == 42)

False


In [7]:
def hint_username(username):
    if len(username) < 0:
        print ('sorry you thief')
    else:
        print('welcome home!')

In [10]:
def is_even(number):
    if number % 2 == 0:
        return True
    return False
is_even(18)
is_even(17)

False

In [16]:
def number(x):
    if x > 5:
        print('x is greater than five')
    elif x < 5:
        print('x is less than five')
    else:
        print('x is equal to five')
number(5)

x is equal to five


In [21]:
product = 1
for n in range (1, 10):
    product = product* n
print(product)

362880


In [22]:
def to_celcius(x):
    return (x - 32) * 5/9
for x in range (0, 101,10):
    print (x, to_celcius(x))

0 -17.77777777777778
10 -12.222222222222221
20 -6.666666666666667
30 -1.1111111111111112
40 4.444444444444445
50 10.0
60 15.555555555555555
70 21.11111111111111
80 26.666666666666668
90 32.22222222222222
100 37.77777777777778


In [47]:
y = [1, 2, 3]
for num in y:
    print(num)

print(num)

1
2
3
3


In [88]:
students = [['Igor', 'Sokolov'], ['Riko', 'Miyazaki'], ['Tuva', 'Johansen']]
for student in students:
   for name in student:
        print(name)
   print()

Igor
Sokolov

Riko
Miyazaki

Tuva
Johansen



In [90]:
greeting ="what's up, \nbrou."
print (greeting)

what's up, 
brou.


In [92]:
my_string = 'Mississippi half-step'
print(my_string[0])

my_list = [1, 'unladen', 'swallow']
print(my_list[0])

print(my_list[-2])

M
1
unladen


In [96]:
my_list = [1, 'unladen', 'swallow']
my_list [1]

'unladen'

In [107]:
brothers = 'bryan and edbert'
brothers[2]

'y'

In [106]:
brothers = 'bryan and edbert'
brothers.index('e')

10

In [108]:
brothers = 'bryan and edbert'
brothers[ 2:5]

'yan'

In [112]:
print('kusno' in brothers)
print('yan' in brothers)


False
True


In [114]:
name = 'Sila'
number = 10
print('OMG, {} has come and will give us {} gifts'.format(name, number))

OMG, Sila has come and will give us 10 gifts


In [117]:
var_a = 'A'
var_b = 'B'
print('{a}, {b}'.format(b=var_b, a=var_a))

A, B


In [118]:
print('{0}{1}{0}'.format('Zu', 'Za'))

ZuZaZu


In [119]:
var_a = 4
var_b = 5
print(f'{var_a} + {var_b}')
print(f'{var_a + var_b}')
print(f'var_a = {var_a} \nvar_b = {var_b}')

4 + 5
9
var_a = 4 
var_b = 5


In [129]:
num = 1000.987123
print(f'{num:.2f}')

num = 1000.987123
print(f'{num:.8e}')

decimal = 0.2497856
print(f'{decimal:.2%}')


1000.99
1.00098712e+03
24.98%


In [141]:
separator_string = ' '
iterable_of_strings = ['Happy', 'birthday', 'to', 'you']

separator_string.join(iterable_of_strings)

'Happy birthday to you'

In [143]:
my_string = 'Do you know the muffin man?'

my_string.split()

['Do', 'you', 'know', 'the', 'muffin', 'man?']

In [144]:
import re

my_string = 'Three sad tigers swallowed wheat in a wheat field'

re.search('[bms]ad', my_string)

<re.Match object; span=(6, 9), match='sad'>

In [145]:
my_string = 'Hey Hoy Hoy'

print(my_string.count('y'))
print(my_string.count('y', 2, 4))

3
1


In [156]:
x = ['hi', 'my','name', 'is', 'human']
print(x[4])
print(x[1:2])
print(x[:2])
print(type(x))
print('hi' in x)

human
['my']
['hi', 'my']
<class 'list'>
True


In [157]:
Planet = ['Earth', 'Mars','Neptune', 'Jupyter', 'Pluto']
print(Planet)


['Earth', 'Mars', 'Neptune', 'Jupyter', 'Pluto']


In [165]:
Planet.append('Saturn')
print(Planet)


['Earth', 'Saturn', 'Mars', 'Neptune', 'Jupyter', 'Pluto', 'Saturn', 'Saturn', 'Saturn', 'Saturn', 'Saturn']


In [166]:
Planet.insert(1,'Saturn')
print(Planet)

['Earth', 'Saturn', 'Saturn', 'Mars', 'Neptune', 'Jupyter', 'Pluto', 'Saturn', 'Saturn', 'Saturn', 'Saturn', 'Saturn']


In [167]:
Planet.remove('Saturn')
print(Planet)

['Earth', 'Saturn', 'Mars', 'Neptune', 'Jupyter', 'Pluto', 'Saturn', 'Saturn', 'Saturn', 'Saturn', 'Saturn']


In [168]:
Planet.pop(3)
print(Planet)

['Earth', 'Saturn', 'Mars', 'Jupyter', 'Pluto', 'Saturn', 'Saturn', 'Saturn', 'Saturn', 'Saturn']


In [169]:
my_list = ['Macduff', 'Malcolm', 'Duncan', 'Banquo']
my_list[2] = 'Macbeth'
print(my_list)

['Macduff', 'Malcolm', 'Macbeth', 'Banquo']


In [170]:
num_list = [2, 4, 6]
print(5 in num_list)
print(5 not in num_list)

False
True


In [171]:
my_list = ['a', 'b', 'd']
my_list.insert(2, 'c')
print(my_list)

['a', 'b', 'c', 'd']


In [172]:
num_list = [1, 2, 3]
num_list[0] = 5446
print(num_list)

[5446, 2, 3]


In [2]:
print(list('rocks'))
print(list(('stones', 'water', 'underground')))

['r', 'o', 'c', 'k', 's']
['stones', 'water', 'underground']


In [7]:
power = '1221'
powers = power + ' volt'
print(powers)
#string has to be with string

1221 volt


In [8]:
fullname = ['Bryan', 'Khan']
fullname = tuple(fullname)
print(fullname)
#change list to tuple

('Bryan', 'Khan')


In [18]:
fullname = ('Bryan', 'Khan')
print(fullname)
#list

('Bryan', 'Khan')


In [19]:
fullname = fullname + ('Hello',)
print(fullname)

('Bryan', 'Khan', 'Hello')


In [26]:
def to (price):
    dollar = int(price// 1)
    cent = round(price% 1*100)

    return dollar, cent
to(60.77)

(60, 77)

In [29]:
dollar, cent = to (60.55)
print(dollar +1)
type(dollar)

61


int

In [51]:
#Using triple quotes to write a string over multiple lines will insert newlines (\n).

sport = """
marathon
golfcart
"""
print(sport)


marathon
golfcart



In [61]:
dominoes =[]
for i in range(5):
    for j in range (5):
        dominoes.append((i,j))
dominoes

[(0, 0),
 (0, 1),
 (0, 2),
 (0, 3),
 (0, 4),
 (1, 0),
 (1, 1),
 (1, 2),
 (1, 3),
 (1, 4),
 (2, 0),
 (2, 1),
 (2, 2),
 (2, 3),
 (2, 4),
 (3, 0),
 (3, 1),
 (3, 2),
 (3, 3),
 (3, 4),
 (4, 0),
 (4, 1),
 (4, 2),
 (4, 3),
 (4, 4)]

In [76]:
dominoes[8][0]

1

In [81]:
pip = [domino[0]+ domino[1] for domino in dominoes]
pip == pip

True

In [87]:
cities = ['Paris', 'Lagos', 'Mumbai']
countries = ['France', 'Nigeria', 'India']
places = zip(cities, countries)


print(places)
print(list(places))
#zipping

[('Paris', 'France'), ('Lagos', 'Nigeria'), ('Mumbai', 'India')]


In [88]:
#unzipping
scientists = [('Nikola', 'Tesla'), ('Charles', 'Darwin'), ('Marie', 'Curie')]
given_names, surnames = zip(*scientists)
print(given_names)
print(surnames)

('Nikola', 'Charles', 'Marie')
('Tesla', 'Darwin', 'Curie')


In [92]:
#enumerate, alwyas start from 0
letters = ['a', 'b', 'c']
for index, letter in enumerate(letters, 3):
   print(index, letter)

3 a
4 b
5 c


In [98]:
#list comprehension
numbers = [1, 2, 3, 4, 5]
new_list = [x + 10 for x in numbers]
print(new_list)

[11, 12, 13, 14, 15]


In [101]:
words = ['Emotan', 'Amina', 'Ibeno', 'Sankwala']
new_list = [(word[0], word[-1]) for word in words if len(word) > 2]
print(new_list)


[('E', 'n'), ('A', 'a'), ('I', 'o'), ('S', 'a')]


In [110]:
#dictionary
my_dict = {'nums': [1, 2, 3],
          'abc': ['a', 'b', 'c']
          }
print(my_dict['abc'])

['a', 'b', 'c']


In [111]:
#Assign new keys
my_dict = {'nums': [1, 2, 3],
          'abc': ['a', 'b', 'c']
          }


# Add a new 'floats' key
my_dict['floats'] = [1.0, 2.0, 3.0]
print(my_dict)

{'nums': [1, 2, 3], 'abc': ['a', 'b', 'c'], 'floats': [1.0, 2.0, 3.0]}


In [117]:
smallest_countries = {'Africa': 'Seychelles',
                     'Asia': 'Maldives',
                     'Europe': 'Vatican City',
                     'Oceania': 'Nauru',
                     'North America': 'St. Kitts and Nevis',
                     'South America': 'Suriname'
                     }


print('Africa' in smallest_countries)
print('Asia' not in smallest_countries)
#check value existance in dictioanry

True
False


In [113]:
#items
my_dict = {'nums': [1, 2, 3],
          'abc': ['a', 'b', 'c']
          }
print(my_dict.items())

dict_items([('nums', [1, 2, 3]), ('abc', ['a', 'b', 'c'])])


In [125]:
#sets
example_b = ('apple', (1, 2, 2, 2, 3), 2)
set(example_b)

{(1, 2, 2, 2, 3), 2, 'apple'}

In [126]:
#frozenset
example_e = [1.5, frozenset(['a', 'b', 'c']), 1.5]
set(example_e)

{1.5, frozenset({'a', 'b', 'c'})}

In [127]:
#Set method

#union
set_1 = {'a', 'b', 'c'}
set_2 = {'b', 'c', 'd'}

print(set_1.union(set_2))
print(set_1 | set_2)

#intersection
print(set_1.intersection(set_2))
print(set_1 & set_2)

#difference
print(set_1.difference(set_2))
print(set_1 - set_2)

#symetric difference
print(set_1.symmetric_difference(set_2))
print(set_1 ^ set_2)


{'b', 'd', 'c', 'a'}
{'b', 'd', 'c', 'a'}
{'c', 'b'}
{'c', 'b'}
{'a'}
{'a'}
{'d', 'a'}
{'d', 'a'}


In [129]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [130]:
list_a = [1,2,3]
list_b = [4,5,6]



In [132]:
a = np.array(list_a)
b = np.array(list_b)

a *b

array([ 4, 10, 18])

In [134]:
import math  
print(math.exp(0))          # e**0
print(math.log(1))          # ln(1)
print(math.factorial(4))    # 4! 
print(math.sqrt(100))       # square root of 100

1.0
0.0
24
10.0


In [133]:
import datetime as dt
today = dt.date.today()           # assign today's date to a variable
print(today)                            # print today's date
print(today.year)                       # print the year today is in

delta = dt.timedelta(days=30)     # assign a timedelta of 30 days to a 
                                        # variable
print(today - delta)

2023-07-21
2023
2023-06-21


In [164]:
import random
print(random.random())          # 0.0 <= X < 1.0
print(random.choice([1, 2, 3, 4, 5])) # choose a random element from a sequence
print(random.randint(1, 1000))    # a <= X <= b

0.9858575352874356
3
360


In [169]:
arr = np.array([1,2,3])
arr.dtype



(3,)

In [170]:
arr.shape

(3,)

In [171]:
arr.ndim

1

In [176]:
good = np.array([[1,2,3],[3,4,5],[5,6,7]])
print(good.shape)
print(good.ndim)
good

(3, 3)
2


array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [179]:
arr = np.array([1, 2, 3, 4])
np.mean(arr)

2.5

In [180]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [181]:
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
array_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [188]:
print(np.zeros((3, 2)))

print(np.ones((2,2))) 


print(np.full((5,3),8))

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[8 8 8]
 [8 8 8]
 [8 8 8]
 [8 8 8]
 [8 8 8]]


In [191]:
array_2d = np.array([(1, 2, 3), (4, 5, 6)])
print(array_2d)

array_2d.flatten()
#ndarray.flatten

[[1 2 3]
 [4 5 6]]



array([1, 2, 3, 4, 5, 6])

In [192]:
#ndarray.reshape
array_2d = np.array([(1, 2, 3), (4, 5, 6)])
print(array_2d)

array_2d.reshape(3, 2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [193]:
array_2d = np.array([(1, 2, 3), (4, 5, 6)])
print(array_2d)
print()
array_2d.reshape(3, -1)

[[1 2 3]
 [4 5 6]]



array([[1, 2],
       [3, 4],
       [5, 6]])

In [194]:
array_2d = np.array([(1, 2, 3), (4, 5, 6)])
print(array_2d)
print()
array_2d.tolist()
#ndarray.tolist

[[1 2 3]
 [4 5 6]]



[[1, 2, 3], [4, 5, 6]]

In [205]:
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)
print()
#MAthematical function
print(a.max())
print(a.mean())
print(a.min())
print(a.std())

print()
#attribute
print(array_2d.shape)
print(array_2d.dtype)
print(array_2d.size)
print(array_2d.T)

#indexing and slicing
print()
print(a[1])
print(a[0, 1])
print(a[1, 2])

print()

a[:, :]

[[1 2 3]
 [4 5 6]]

6
3.5
1
1.707825127659933

(2, 3)
int32
6
[[1 4]
 [2 5]
 [3 6]]

[4 5 6]
2
6



array([[1, 2, 3],
       [4, 5, 6]])

In [208]:
#mutability
a = np.array([(1, 2), (3, 4)])
print(a)
print()

a[1][1] = 100
a

[[1 2]
 [3 4]]



array([[  1,   2],
       [  3, 100]])

In [211]:
d = {'col1': [1, 2], 'col2': [3, 4]}
df = pd.DataFrame(data=d)
df

col1  col2
0     1     3
1     2     4

In [212]:
df2 = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
                  columns=['a', 'b', 'c'])
df2

a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [229]:
#loc
df = pd.DataFrame({
   'A': ['alpha', 'apple', 'arsenic', 'angel', 'android'],
   'B': [1, 2, 3, 4, 5],
   'C': ['coconut', 'curse', 'cassava', 'cuckoo', 'clarinet'],
   'D': [6, 7, 8, 9, 10]
   },
   index=['row_0', 'row_1', 'row_2', 'row_3', 'row_4'])
df

print()

print(df.loc['row_1'])

print()

print(df.loc['row_1'])

print()

print(df.loc[['row_1']])

print()

print(df.loc['row_0':'row_2'])

print()
print(df.loc[:, ['B', 'D']])
# all rows were selected using just a colon (:).



A    apple
B        2
C    curse
D        7
Name: row_1, dtype: object

A    apple
B        2
C    curse
D        7
Name: row_1, dtype: object

           A  B      C  D
row_1  apple  2  curse  7

             A  B        C  D
row_0    alpha  1  coconut  6
row_1    apple  2    curse  7
row_2  arsenic  3  cassava  8

       B   D
row_0  1   6
row_1  2   7
row_2  3   8
row_3  4   9
row_4  5  10


In [232]:
#iloc
print(df.iloc[1])

print()

print(df.iloc[[1]])

print()

print(df.iloc[[0, 2, 4]])

print()

print(df.iloc[0:3])

print()
print(df.iloc[:, [1,3]])
# all rows were selected using just a colon (:).


A    apple
B        2
C    curse
D        7
Name: row_1, dtype: object

           A  B      C  D
row_1  apple  2  curse  7

             A  B         C   D
row_0    alpha  1   coconut   6
row_2  arsenic  3   cassava   8
row_4  android  5  clarinet  10

             A  B        C  D
row_0    alpha  1  coconut  6
row_1    apple  2    curse  7
row_2  arsenic  3  cassava  8

       B   D
row_0  1   6
row_1  2   7
row_2  3   8
row_3  4   9
row_4  5  10


In [228]:
#row and column selection 
print(df.iloc[[2, 4], 0:3])

print()

print(df.loc[0:3, ['D']])

print()

# This is most convenient for VIEWING: 
print(df.iloc[0:3][['D']])

# But this is best practice/more stable for assignment/manipulation:
print(df.loc[df.index[0:3], 'D'])

print()

row_0     coconut
row_1       curse
row_2     cassava
row_3      cuckoo
row_4    clarinet
Name: C, dtype: object





In [254]:
data = {'planet': ['Mercury', 'Venus', 'Earth', 'Mars',
                   'Jupiter', 'Saturn', 'Uranus', 'Neptune'],
       'radius_km': [2440, 6052, 6371, 3390, 69911, 58232,
                     25362, 24622],
       'moons': [0, 0, 1, 2, 80, 83, 27, 14]
        }
df = pd.DataFrame(data)
print(df)

print()
print(df['moons'] < 20)

print()
print(df[df['moons'] < 20])


#other way
print()

print(df[df['moons'] < 20])

#other way 2
print()
mask = df['moons'] < 20
df2 = df[mask]
df2

    planet  radius_km  moons
0  Mercury       2440      0
1    Venus       6052      0
2    Earth       6371      1
3     Mars       3390      2
4  Jupiter      69911     80
5   Saturn      58232     83
6   Uranus      25362     27
7  Neptune      24622     14

0     True
1     True
2     True
3     True
4    False
5    False
6    False
7     True
Name: moons, dtype: bool

    planet  radius_km  moons
0  Mercury       2440      0
1    Venus       6052      0
2    Earth       6371      1
3     Mars       3390      2
7  Neptune      24622     14

    planet  radius_km  moons
0  Mercury       2440      0
1    Venus       6052      0
2    Earth       6371      1
3     Mars       3390      2
7  Neptune      24622     14



planet  radius_km  moons
0  Mercury       2440      0
1    Venus       6052      0
2    Earth       6371      1
3     Mars       3390      2
7  Neptune      24622     14

In [257]:
#logical Statements
mask = (df['moons'] < 10) | (df['moons'] > 50)
mask

0     True
1     True
2     True
3     True
4     True
5     True
6    False
7    False
Name: moons, dtype: bool

In [258]:
#logical Statements
mask = (df['moons'] < 10) | (df['moons'] > 50)
df[mask]

planet  radius_km  moons
0  Mercury       2440      0
1    Venus       6052      0
2    Earth       6371      1
3     Mars       3390      2
4  Jupiter      69911     80
5   Saturn      58232     83

In [256]:
mask = (df['moons'] > 20) & (df['moons'] != 80) & (df['radius_km'] >= 50000)
df[mask]

planet  radius_km  moons
5  Saturn      58232     83

In [272]:
clothes = pd.DataFrame({'type': ['pants', 'shirt', 'shirt', 'pants', 'shirt', 'pants'],
                       'color': ['red', 'blue', 'green', 'blue', 'green', 'red'],
                       'price_usd': [20, 35, 50, 40, 100, 75],
                       'mass_g': [125, 440, 680, 200, 395, 485]})


clothes

type  color  price_usd  mass_g
0  pants    red         20     125
1  shirt   blue         35     440
2  shirt  green         50     680
3  pants   blue         40     200
4  shirt  green        100     395
5  pants    red         75     485

In [273]:
grouped = clothes.groupby('type')
print(grouped)

In [274]:
clothes.groupby(['type'])

In [285]:
clothes.groupby(['type']).sum()

C:\Users\Santasila Bryan Kusn\AppData\Local\Temp\ipykernel_19156\2359364155.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  clothes.groupby(['type']).sum()


price_usd  mass_g
type                    
pants        135     810
shirt        185    1515

In [289]:
clothes.groupby(['type', 'color']).min()

price_usd  mass_g
type  color                   
pants blue          40     200
      red           20     125
shirt blue          35     440
      green         50     395

In [277]:
clothes.groupby(['type', 'color']).size()

type   color
pants  blue     1
       red      2
shirt  blue     1
       green    2
dtype: int64

In [278]:
clothes[['price_usd', 'mass_g']].agg(['sum', 'mean'])

price_usd  mass_g
sum   320.000000  2325.0
mean   53.333333   387.5

In [279]:
clothes.agg({'price_usd': 'sum',
            'mass_g': ['mean', 'median']
            })

price_usd  mass_g
sum         320.0     NaN
mean          NaN   387.5
median        NaN   417.5

In [280]:
clothes[['price_usd', 'mass_g']].agg(['sum', 'mean'], axis=1)

sum   mean
0  145.0   72.5
1  475.0  237.5
2  730.0  365.0
3  240.0  120.0
4  495.0  247.5
5  560.0  280.0

In [281]:

clothes.groupby('color').agg({'price_usd': ['mean', 'max'],
                             'mass_g': ['mean', 'max']})

price_usd      mass_g     
           mean  max   mean  max
color                           
blue       37.5   40  320.0  440
green      75.0  100  537.5  680
red        47.5   75  305.0  485